name: "projects_and_vacancies"
services:
  db:
    container_name: "projects_and_vacancies_db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "projects-and-vacancies"
      POSTGRES_USER: "USERNAME"
    restart: "unless-stopped"
