name: "projects_and_vacancies"
services:
  db:
    container_name: "projects_and_vacancies_db"
    image: postgres
    ports:
      - "35432:5432"
    environment:
      POSTGRES_PASSWORD: "_p455W0Rd_"
      POSTGRES_DB: "projects_and_vacancies"
    #    volumes:
    #      - ""
    restart: "unless-stopped"