name: "projects_and_vacancies"
services:
  db:
    container_name: "projects_and_vacancies_db"
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "PASSWORD"
      POSTGRES_DB: "projects-and-vacancies"
      POSTGRES_USER: "USERNAME"
    restart: "unless-stopped"

  app:
    container_name: "projects_and_vacancies_app"
    image: gradle
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/projects-and-vacancies"
    volumes:
      - ./.:/host
    working_dir: /host
    command: "bash gradlew bootRun"
